// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/order/order.proto
//
// NOTE: This file was manually created for educational purposes.
// In production, you would generate this using:
//   protoc --go_out=. proto/order/order.proto

package order

import (
	"time"
)

// OrderStatus enum for order states
type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED OrderStatus = 0
	OrderStatus_ORDER_STATUS_PENDING     OrderStatus = 1
	OrderStatus_ORDER_STATUS_PAID        OrderStatus = 2
	OrderStatus_ORDER_STATUS_PROCESSING  OrderStatus = 3
	OrderStatus_ORDER_STATUS_SHIPPED     OrderStatus = 4
	OrderStatus_ORDER_STATUS_DELIVERED   OrderStatus = 5
	OrderStatus_ORDER_STATUS_CANCELLED   OrderStatus = 6
)

func (s OrderStatus) String() string {
	switch s {
	case OrderStatus_ORDER_STATUS_PENDING:
		return "PENDING"
	case OrderStatus_ORDER_STATUS_PAID:
		return "PAID"
	case OrderStatus_ORDER_STATUS_PROCESSING:
		return "PROCESSING"
	case OrderStatus_ORDER_STATUS_SHIPPED:
		return "SHIPPED"
	case OrderStatus_ORDER_STATUS_DELIVERED:
		return "DELIVERED"
	case OrderStatus_ORDER_STATUS_CANCELLED:
		return "CANCELLED"
	default:
		return "UNSPECIFIED"
	}
}

// OrderItem represents a single item in an order
type OrderItem struct {
	ProductID      string `json:"product_id"`
	ProductName    string `json:"product_name"`
	Quantity       int32  `json:"quantity"`
	UnitPriceCents int64  `json:"unit_price_cents"`
}

// Order represents an order in the system
type Order struct {
	// ID is the unique order identifier
	ID string `json:"id"`

	// CustomerID of the customer who placed the order
	CustomerID string `json:"customer_id"`

	// CustomerEmail for notifications
	CustomerEmail string `json:"customer_email"`

	// Items in the order
	Items []OrderItem `json:"items"`

	// TotalCents is the total amount in cents
	TotalCents int64 `json:"total_cents"`

	// Currency code (e.g., "BRL", "USD")
	Currency string `json:"currency"`

	// Status is the current order status
	Status OrderStatus `json:"status"`

	// PaymentTransactionID is set after successful payment
	PaymentTransactionID string `json:"payment_transaction_id,omitempty"`

	// Timestamps
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// OrderCreatedEvent is published when a new order is created
// This is the main event that triggers downstream processing
type OrderCreatedEvent struct {
	// EventID is a unique identifier for this event
	EventID string `json:"event_id"`

	// EventType is always "order.created"
	EventType string `json:"event_type"`

	// Timestamp when the event was created
	Timestamp time.Time `json:"timestamp"`

	// Order is the full order data
	Order Order `json:"order"`
}

// OrderPaidEvent is published when payment is confirmed
type OrderPaidEvent struct {
	EventID       string    `json:"event_id"`
	EventType     string    `json:"event_type"`
	Timestamp     time.Time `json:"timestamp"`
	OrderID       string    `json:"order_id"`
	TransactionID string    `json:"transaction_id"`
	AmountCents   int64     `json:"amount_cents"`
}

// OrderCancelledEvent is published when an order is cancelled
type OrderCancelledEvent struct {
	EventID   string    `json:"event_id"`
	EventType string    `json:"event_type"`
	Timestamp time.Time `json:"timestamp"`
	OrderID   string    `json:"order_id"`
	Reason    string    `json:"reason"`
}

// NewOrderCreatedEvent creates a new OrderCreatedEvent
func NewOrderCreatedEvent(order Order) OrderCreatedEvent {
	return OrderCreatedEvent{
		EventID:   "evt_" + order.ID,
		EventType: "order.created",
		Timestamp: time.Now(),
		Order:     order,
	}
}

// NewOrderPaidEvent creates a new OrderPaidEvent
func NewOrderPaidEvent(orderID, transactionID string, amountCents int64) OrderPaidEvent {
	return OrderPaidEvent{
		EventID:       "evt_paid_" + orderID,
		EventType:     "order.paid",
		Timestamp:     time.Now(),
		OrderID:       orderID,
		TransactionID: transactionID,
		AmountCents:   amountCents,
	}
}
