// Package payment provides types and gRPC service definitions for payment processing.
// NOTE: In production, these would be generated by protoc from payment.proto
package payment

import (
	"time"

	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoimpl"
)

// PaymentStatus enum for payment states
type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_PENDING     PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_COMPLETED   PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_FAILED      PaymentStatus = 3
	PaymentStatus_PAYMENT_STATUS_REFUNDED    PaymentStatus = 4
)

func (s PaymentStatus) String() string {
	switch s {
	case PaymentStatus_PAYMENT_STATUS_PENDING:
		return "PENDING"
	case PaymentStatus_PAYMENT_STATUS_COMPLETED:
		return "COMPLETED"
	case PaymentStatus_PAYMENT_STATUS_FAILED:
		return "FAILED"
	case PaymentStatus_PAYMENT_STATUS_REFUNDED:
		return "REFUNDED"
	default:
		return "UNSPECIFIED"
	}
}

// PaymentErrorCode enum for specific error types
type PaymentErrorCode int32

const (
	PaymentErrorCode_PAYMENT_ERROR_CODE_UNSPECIFIED        PaymentErrorCode = 0
	PaymentErrorCode_PAYMENT_ERROR_CODE_INSUFFICIENT_FUNDS PaymentErrorCode = 1
	PaymentErrorCode_PAYMENT_ERROR_CODE_INVALID_CARD       PaymentErrorCode = 2
	PaymentErrorCode_PAYMENT_ERROR_CODE_LIMIT_EXCEEDED     PaymentErrorCode = 3
	PaymentErrorCode_PAYMENT_ERROR_CODE_PROCESSING_ERROR   PaymentErrorCode = 4
	PaymentErrorCode_PAYMENT_ERROR_CODE_DUPLICATE_REQUEST  PaymentErrorCode = 5
)

func (c PaymentErrorCode) String() string {
	switch c {
	case PaymentErrorCode_PAYMENT_ERROR_CODE_INSUFFICIENT_FUNDS:
		return "INSUFFICIENT_FUNDS"
	case PaymentErrorCode_PAYMENT_ERROR_CODE_INVALID_CARD:
		return "INVALID_CARD"
	case PaymentErrorCode_PAYMENT_ERROR_CODE_LIMIT_EXCEEDED:
		return "LIMIT_EXCEEDED"
	case PaymentErrorCode_PAYMENT_ERROR_CODE_PROCESSING_ERROR:
		return "PROCESSING_ERROR"
	case PaymentErrorCode_PAYMENT_ERROR_CODE_DUPLICATE_REQUEST:
		return "DUPLICATE_REQUEST"
	default:
		return "UNSPECIFIED"
	}
}

// Ensure we implement proto.Message interface
var (
	_ proto.Message = (*PaymentRequest)(nil)
	_ proto.Message = (*PaymentResponse)(nil)
	_ proto.Message = (*PaymentStatusRequest)(nil)
	_ proto.Message = (*PaymentStatusResponse)(nil)
)

// PaymentRequest contains the data needed to process a payment
type PaymentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdempotencyKey string `protobuf:"bytes,1,opt,name=idempotency_key,proto3" json:"idempotency_key,omitempty"`
	OrderID        string `protobuf:"bytes,2,opt,name=order_id,proto3" json:"order_id,omitempty"`
	AmountCents    int64  `protobuf:"varint,3,opt,name=amount_cents,proto3" json:"amount_cents,omitempty"`
	Currency       string `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	CustomerEmail  string `protobuf:"bytes,5,opt,name=customer_email,proto3" json:"customer_email,omitempty"`
	PaymentMethod  string `protobuf:"bytes,6,opt,name=payment_method,proto3" json:"payment_method,omitempty"`
}

func (x *PaymentRequest) Reset()                               { *x = PaymentRequest{} }
func (x *PaymentRequest) String() string                       { return "PaymentRequest" }
func (*PaymentRequest) ProtoMessage()                          {}
func (*PaymentRequest) ProtoReflect() protoreflect.Message     { return nil }
func (*PaymentRequest) Descriptor() ([]byte, []int)            { return nil, nil }

func (x *PaymentRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *PaymentRequest) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

func (x *PaymentRequest) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *PaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PaymentRequest) GetCustomerEmail() string {
	if x != nil {
		return x.CustomerEmail
	}
	return ""
}

// PaymentResponse contains the result of payment processing
type PaymentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success       bool             `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TransactionID string           `protobuf:"bytes,2,opt,name=transaction_id,proto3" json:"transaction_id,omitempty"`
	ErrorCode     PaymentErrorCode `protobuf:"varint,3,opt,name=error_code,proto3" json:"error_code,omitempty"`
	ErrorMessage  string           `protobuf:"bytes,4,opt,name=error_message,proto3" json:"error_message,omitempty"`
	ProcessedAt   time.Time        `protobuf:"bytes,5,opt,name=processed_at,proto3" json:"processed_at,omitempty"`
}

func (x *PaymentResponse) Reset()                               { *x = PaymentResponse{} }
func (x *PaymentResponse) String() string                       { return "PaymentResponse" }
func (*PaymentResponse) ProtoMessage()                          {}
func (*PaymentResponse) ProtoReflect() protoreflect.Message     { return nil }
func (*PaymentResponse) Descriptor() ([]byte, []int)            { return nil, nil }

func (x *PaymentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PaymentResponse) GetTransactionID() string {
	if x != nil {
		return x.TransactionID
	}
	return ""
}

func (x *PaymentResponse) GetErrorCode() PaymentErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return PaymentErrorCode_PAYMENT_ERROR_CODE_UNSPECIFIED
}

func (x *PaymentResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// PaymentStatusRequest for querying payment status
type PaymentStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransactionID string `protobuf:"bytes,1,opt,name=transaction_id,proto3" json:"transaction_id,omitempty"`
}

func (x *PaymentStatusRequest) Reset()                               { *x = PaymentStatusRequest{} }
func (x *PaymentStatusRequest) String() string                       { return "PaymentStatusRequest" }
func (*PaymentStatusRequest) ProtoMessage()                          {}
func (*PaymentStatusRequest) ProtoReflect() protoreflect.Message     { return nil }
func (*PaymentStatusRequest) Descriptor() ([]byte, []int)            { return nil, nil }

func (x *PaymentStatusRequest) GetTransactionID() string {
	if x != nil {
		return x.TransactionID
	}
	return ""
}

// PaymentStatusResponse with payment details
type PaymentStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransactionID string        `protobuf:"bytes,1,opt,name=transaction_id,proto3" json:"transaction_id,omitempty"`
	OrderID       string        `protobuf:"bytes,2,opt,name=order_id,proto3" json:"order_id,omitempty"`
	AmountCents   int64         `protobuf:"varint,3,opt,name=amount_cents,proto3" json:"amount_cents,omitempty"`
	Currency      string        `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Status        PaymentStatus `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     time.Time     `protobuf:"bytes,6,opt,name=created_at,proto3" json:"created_at,omitempty"`
}

func (x *PaymentStatusResponse) Reset()                               { *x = PaymentStatusResponse{} }
func (x *PaymentStatusResponse) String() string                       { return "PaymentStatusResponse" }
func (*PaymentStatusResponse) ProtoMessage()                          {}
func (*PaymentStatusResponse) ProtoReflect() protoreflect.Message     { return nil }
func (*PaymentStatusResponse) Descriptor() ([]byte, []int)            { return nil, nil }

func (x *PaymentStatusResponse) GetTransactionID() string {
	if x != nil {
		return x.TransactionID
	}
	return ""
}

func (x *PaymentStatusResponse) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

func (x *PaymentStatusResponse) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *PaymentStatusResponse) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}
